### ISSUE TITLE
Uploader password

### ISSUE THREAD

**Issue by fastfinge** [YunoHost-Apps/microbin_ynh#2]
By default, microbin_readonly should probably be set, with the uploader password the same as the admin password.  If you want to use microbin to share temporary files to the public, you probably don't want to also let anyone on the internet use your server to store absolutely anything. But that's the way it's configured in yunohost.  Or at least, setting an uploader password should be an option during install of the package.

**Comment by ericgaspar** [comment]
Thanks. If you want to change default settings, the environment file is now located in `/etc/www/microbin/.env`. You will need to restart systemd for the changes to take effect.
